rvm:
  - 1.8.7
  - 1.9.2
  - jruby
  - ree
env:
  - DB=mysql
  - DB=postgres
before_script:
  - "mysql -e 'create database social_stream_test;'"
  - "psql -c 'create database social_stream_test;' -U postgres"
